import { schema as s } from "@/lib/db"
import { defineProduct } from "@/lib/product"

const locations = { table: s.inventoryLocations, label: "name" }
const suppliers = { table: s.suppliers, label: "name" }
const products = { table: s.products, label: "name" }

export const product = defineProduct({
  name: "Manifest",
  tagline: "Inventory operations: purchasing, fulfilment, transfers and quality, all in one ledger.",
  accent: "#c8ff3d",
  resources: [
    {
      key: "purchase-orders",
      label: "Purchase orders",
      singular: "Purchase order",
      description: "Stock you've ordered from suppliers, from sent to received.",
      table: s.purchaseOrders,
      list: ["orderNumber", "supplierId", "status", "targetDate", "totalAmount"],
      form: ["orderNumber", "supplierId", "status", "supplierReference", "orderDate", "targetDate", "subtotal", "taxAmount", "shippingCost", "totalAmount", "notes", "internalNotes"],
      refs: { supplierId: suppliers },
      generate: { orderNumber: "PO" },
      status: "status",
      money: ["subtotal", "taxAmount", "shippingCost", "totalAmount"],
    },
    {
      key: "sales-orders",
      label: "Sales orders",
      singular: "Sales order",
      description: "Wholesale and B2B orders from confirmation to delivery.",
      table: s.salesOrders,
      list: ["orderNumber", "customerName", "status", "targetDate", "totalAmount"],
      form: ["orderNumber", "customerName", "customerEmail", "customerPhone", "status", "orderDate", "targetDate", "subtotal", "taxAmount", "shippingCost", "discountAmount", "totalAmount", "shippingMethod", "trackingNumber", "trackingUrl", "notes", "internalNotes"],
      generate: { orderNumber: "SO" },
      status: "status",
      money: ["subtotal", "taxAmount", "shippingCost", "discountAmount", "totalAmount"],
    },
    {
      key: "transfers",
      label: "Transfers",
      singular: "Transfer",
      description: "Move stock between warehouses, venues and storage.",
      table: s.transferOrders,
      list: ["orderNumber", "fromLocationId", "toLocationId", "status", "expectedDate"],
      form: ["orderNumber", "fromLocationId", "toLocationId", "status", "totalQuantity", "expectedDate", "shippingMethod", "trackingNumber", "shippingCost", "notes"],
      refs: { fromLocationId: locations, toLocationId: locations },
      generate: { orderNumber: "TR" },
      status: "status",
      money: ["shippingCost"],
    },
    {
      key: "returns",
      label: "Returns",
      singular: "Return",
      description: "RMAs from request through refund.",
      table: s.returnOrders,
      list: ["returnNumber", "customerName", "status", "reason", "refundAmount"],
      form: ["returnNumber", "rmaNumber", "customerName", "customerEmail", "status", "reason", "reasonCode", "resolution", "refundAmount", "customerNotes", "internalNotes"],
      generate: { returnNumber: "RMA" },
      status: "status",
      money: ["refundAmount"],
    },
    {
      key: "audits",
      label: "Cycle counts",
      singular: "Audit",
      description: "Scheduled stock counts and discrepancy tracking.",
      table: s.inventoryAudits,
      list: ["name", "auditType", "locationId", "status", "scheduledDate"],
      form: ["name", "auditType", "locationId", "status", "scheduledDate", "includeAllProducts", "notes"],
      refs: { locationId: locations },
      status: "status",
    },
    {
      key: "quality",
      label: "Quality checks",
      singular: "Quality check",
      description: "Inspections on incoming stock and finished builds.",
      table: s.qualityChecks,
      list: ["checkNumber", "productId", "checkType", "status", "inspectionDate"],
      form: ["checkNumber", "productId", "checkType", "status", "sampleSize", "lotSize", "passedQuantity", "failedQuantity", "defectCount", "inspectionDate", "disposition", "correctiveAction", "notes"],
      refs: { productId: products },
      generate: { checkNumber: "QC" },
      status: "status",
    },
    {
      key: "build-orders",
      label: "Build orders",
      singular: "Build order",
      description: "Assemble kits, bundles and finished goods from components.",
      table: s.buildOrders,
      list: ["orderNumber", "productId", "quantity", "status", "targetDate"],
      form: ["orderNumber", "productId", "title", "quantity", "quantityCompleted", "status", "locationId", "startDate", "targetDate", "notes"],
      refs: { productId: products, locationId: locations },
      generate: { orderNumber: "BO" },
      status: "status",
    },
    {
      key: "price-lists",
      label: "Price lists",
      singular: "Price list",
      description: "Tiered pricing for wholesale, VIP and distributor customers.",
      table: s.priceLists,
      list: ["name", "pricingTier", "markupPercentage", "discountPercentage", "isActive"],
      form: ["name", "description", "pricingTier", "currency", "markupPercentage", "discountPercentage", "validFrom", "validUntil", "isActive", "isDefault"],
    },
    {
      key: "suppliers",
      label: "Suppliers",
      singular: "Supplier",
      table: s.suppliers,
      list: ["name", "email", "phone", "leadTimeDays", "isActive"],
      form: ["name", "email", "phone", "website", "paymentTerms", "leadTimeDays", "currency", "addressLine1", "city", "state", "country", "isActive", "notes"],
    },
    {
      key: "locations",
      label: "Locations",
      singular: "Location",
      table: s.inventoryLocations,
      list: ["name", "code", "city", "isDefault", "isActive"],
      form: ["name", "code", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "isDefault", "isActive"],
    },
  ],
})
